# Generated by Django 4.2.26 on 2026-04-18 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('codetechies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='issued',
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='contest',
        ),
        migrations.AddField(
            model_name='certificate',
            name='issued_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='title',
            field=models.CharField(default='CodeTechies Completion', max_length=200),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Contest',
        ),
    ]
