# Generated by Django 4.2.26 on 2026-04-18 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codetechies', '0002_remove_certificate_contest_remove_certificate_issued_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='cert_type',
            field=models.CharField(choices=[('participation', 'Participation'), ('completion', 'Completion')], default='participation', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
