# Generated by Django 4.2.26 on 2026-04-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codetechies', '0004_problem_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codetechies.problem'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(default='easy', max_length=10),
        ),
    ]
